config/routes.rb
Rails.application.routes.draw do
  resources :notes

  root 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.js
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="text-center py-3">Miguel González Herrera
    <a href="www.linkedin.com/in/miguel-gonzalez-herrera" target="blank"><i class="fab fa-linkedin"></i></a> 
  </div>

</footer>

app/views/layouts/_header.html.erb
<header class="header">

  <div class="text-center py-3">
    <%= image_tag("alkimii.jpg", :alt => "alkimii", style: 'height:100px;width:100px;') %>
    <h3>SPA on Rails using Jquery and AJAX</h3>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  </head>

  <body>
  <div  class="containerFluid">
    <%= render 'layouts/header' %>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  <div  class="containerFluid">
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit :Create, class: 'btn btn-primary mt-2 mb-5' %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<tr>
    <td><%= note.title %></td>
    <td><%= link_to 'Edit', edit_note_path(note), :class => "btn btn-success" %></td>
    <td><%= link_to 'Destroy', note, method: :delete, data: {confirm: 'Are you sure?', remote: true }, class:"delete btn btn-danger" %></td>
</tr>

app/views/notes/create.js.erb
$('#new-note form').remove()
$('#new-note a').show()
$('table#notes tbody').append("<%= j render @note %>")

app/views/notes/destroy.js.erb
$('.delete').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
})

app/views/notes/edit.html.erb
<div class="mt-5 mb-5">

<%= render 'form', note: @note %>

<div>
<%= link_to 'Back', notes_path, :class => "btn btn-light" %>
</div>
</div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div>
<div id="new-note">
<%= link_to 'New Note', new_note_path, remote: true, :class => "btn btn-secondary mb-5" %>
</div>
<br>
<table id="notes" class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @notes %>
  </tbody>
</table>
</div>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note: %>

<%= link_to 'Back', notes_path %>

app/views/notes/new.js.erb
$("#new-note a").hide().parent().append("<%= j render 'form', note: @note %>")

app/views/notes/show.html.erb
<div class="mt-5 mb-5">
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
  <p>
    <strong>Title:</strong>
    <%= @note.title %>
  </p>

  <div>
    <%= link_to 'Edit', edit_note_path(@note), :class => "btn btn-primary" %>
    <%= link_to 'Back', notes_path, :class => "btn btn-light" %>
  </div>
</div>